
url: "https://username.github.io"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: My website

# Short description of your site
description: A virtual proof that name is awesome!
title: Here it is
author:
  name: Some Person
